### ISSUE TITLE
Lua include path broken

### ISSUE THREAD

**Issue by FadiBitar** [ThePhD/lua-bench#14]
Looking at the Lua github, it looks like the code is not inside a /include folder, which means that the wrappers won't find lua.h
Changing the include paths from "lua/include" to "lua" should solve the problem.
Another issue is that LuaCppInterface checks out its own version of Lua (from a different repository frozen at v5.2), and the include path in the LuaCppInterface points to that version of Lua instead of the common one.
One last issue is that checking out Lua from github comes without the Lua.hpp file, which breaks the compilation. Downloading the corresponding Lua.hpp from the releases tab and placing it in the vendors/lua folder solves the problem, but sort of takes away the "this works out of the box" feeling.

**Comment by ThePhD** [comment]
I don't know what platform you're on to be experiencing these troubles.

All of the wrappers don't include Lua using `include/lua.h`, they just do `lua.h` or similar. It doesn't matter what include directory it's in, as you can simply pass the correct path that puts `lua.h` in an accessible place (as the vcxproj's do).

At the moment, the only build I have going is Visual Studio, because setting up an alternate build system that properly references all of these projects is borderline nightmarish on any other platform and writing the makefiles by hand to compile these projects is beyond painful. It's something I want to work on, but I haven't quite gotten to it yet.

Yes, the lua.hpp is missing. I'm trying to think of a way to supply it, and it _should_ be part of the regular distribution but for some reason is not.

**Comment by FadiBitar** [comment]
In the project files for the following projects, the c++ include paths list "lua\include", which leads to a compilation error of the sorts "cannot open lua.h, file not found":
- lua bench
- vendor/luabind
- vendor/oolua
- vendor/slb3

This is on windows, using visual studio. I believe if you make a clean recursive checkout (to also get the latest lua, which doesn't have a /include folder) you would be able to reproduce the error.

**Comment by ThePhD** [comment]
Finally spent the time to fix this. Thanks for reporting.
